### ISSUE TITLE
Method problem

### ISSUE THREAD

**Issue by algorys** [shinken-monitoring/mod-import-glpi#2]
Hello,

I'm trying to use the module import-glpi, and I have this error in log of arbiter : 
[1428486801] ERROR: [Shinken] Back trace of this remove: Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 346, in load_config_file
r = inst.get_objects()
File "/var/lib/shinken/modules/import-glpi/module.py", line 149, in get_objects
all_hostgroups = self.con.monitoring.shinkenHostgroups(arg)
File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in call
return self.__send(self.__name, args)
File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
verbose=self.__verbose
File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
return self.single_request(host, handler, request_body, verbose)
File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
return self.parse_response(response)
File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
return u.close()
File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
raise Fault(**self._stack[0])
Fault:  <Fault 2: 'Unknown method (monitoring.shinkenHostgroups)'>

Is there a way to "patch" this ? Because I have search on web for this issue, but found nothing to resolve it.

Shinken 2.2 / GLPI 0.84.8

import-gpi.cfg
define module {
    module_name     import-glpi
    module_type     import-glpi
    uri             http://localhost/glpi/plugins/webservices/xmlrpc.php
    login_name      shinken
    login_password  xxxxxx
    tag
}

**Comment by mohierf** [comment]
Ok.

On Glpi, did you installed and configured the plugins : 
- Monitoring ?
- Web services ?

On Shinken, what if you run : 
- shinken-arbiter -v -c /etc/shinken/shinken.cfg
  
  You should have some logs as of it : 

```
[1428497071] INFO: [Shinken] [GLPI Arbiter] Get a Simple GLPI arbiter for plugin import-glpi
[1428497071] INFO: [Shinken] [WS_Arbiter] Configuration done, host: 0.0.0.0(7760), username: anonymous)
[1428497071] INFO: [Shinken] Trying to init module: PickleRetentionArbiter
[1428497071] INFO: [Shinken] Trying to init module: import-glpi
[1428497071] INFO: [Shinken] [GLPI Arbiter] Connecting to http://localhost/glpi/plugins/webservices/xmlrpc.php
[1428497071] INFO: [Shinken] [GLPI Arbiter] Connection opened
[1428497071] INFO: [Shinken] [GLPI Arbiter] Authentication in progress...
[1428497071] INFO: [Shinken] [GLPI Arbiter] Authenticated, session : db4d5nt76n9tqd26g1emk5va52
[1428497071] INFO: [Shinken] I correctly loaded the modules: [PickleRetentionArbiter,import-glpi,ws-arbiter]
[1428497071] INFO: [Shinken] [GLPI Arbiter] Tags: [u'eLiberty']
[1428497071] INFO: [Shinken] [GLPI Arbiter] Getting configuration for entity tagged with 'eLiberty'
[1428497071] WARNING: [Shinken] [GLPI Arbiter] Got 46 commands
[1428497071] INFO: [Shinken] [GLPI Arbiter] New command: pm-check_tcp
[1428497071] INFO: [Shinken] [GLPI Arbiter] New command: pm-check_http
[1428497071] INFO: [Shinken] [GLPI Arbiter] New command: pm-check_https
[1428497071] INFO: [Shinken] [GLPI Arbiter] New command: pm-check_dig
[1428497071] INFO: [Shinken] [GLPI Arbiter] New command: pm-check_ftp
[1428497071] INFO: [Shinken] [GLPI Arbiter] New command: pm-check_nrpe

...
```

**Comment by algorys** [comment]
Sorry,

I had to recover my snapshot with vsphere before. That's good ! :)

I have Monitoring and Services Web installed on GLPI.
On shinken, I have import-glpi, glpidb and ws-arbiter

When I run shinken-arbiter -v -c /etc/shinken/shinken.cfg I have : 

[code]
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_snmp_service.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/detailled-host-by-email.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/restart-shinken.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-host-by-android-sms.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-service-by-android-sms.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-host-by-xmpp.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_nrpe.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_tcp.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/reload-shinken.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/detailled-service-by-email.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-host-by-email.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_ping.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_dig.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/configuration-check.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_nrpe_args.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_host_alive.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-service-by-xmpp.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_snmp_time.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-service-by-email.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_snmp_storage.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/timeperiods/24x7.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/timeperiods/workhours.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/timeperiods/us-holidays.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/timeperiods/none.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/escalations/sample.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/dependencies/sample.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/templates/generic-contact.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/templates/time_templates.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/templates/generic-host.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/templates/generic-service.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/templates/srv-pnp.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/notificationways/sms-android.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/notificationways/email.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/notificationways/detailled-email.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/servicegroups/sample.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/hostgroups/linux.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/contactgroups/users.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/contactgroups/admins.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/hosts/localhost.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/services/services.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/contacts/guest.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/contacts/admin.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/packs/readme.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/modules/glpidb.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/modules/auth_cfg_password.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/modules/sample.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/modules/import-glpi.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/modules/ws_arbiter.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/modules/mongodb.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/modules/webui.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/modules/sqlitedb.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/arbiters/arbiter-master.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/schedulers/scheduler-master.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/pollers/poller-master.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/reactionners/reactionner-android-sms.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/reactionners/reactionner-master.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/brokers/broker-master.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/receivers/receiver-master.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/realms/all.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/resource.d/active-directory.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/resource.d/paths.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/resource.d/snmp.cfg'
[1428497547] INFO: [Shinken] Processing object config file '/etc/shinken/resource.d/nmap.cfg'
[1428497547] INFO: [Shinken] And arbiter is launched with the hostname:dev03 from an arbiter point of view of addr:dev03.alpi-net.com
[1428497547] INFO: [Shinken] I am the master Arbiter: arbiter-master
[1428497547] INFO: [Shinken] My own modules: import-glpi,ws-arbiter
[1428497547] INFO: [Shinken] Modules directory: /var/lib/shinken/modules
[1428497547] INFO: [Shinken] Modules directory: /var/lib/shinken/modules
[1428497547] INFO: [Shinken] [GLPI Arbiter] Get a Simple GLPI arbiter for plugin import-glpi
[1428497547] INFO: [Shinken] [WS_Arbiter] Configuration done, host: 192.168.1.23(7760), username: anonymous)
[1428497547] INFO: [Shinken] Trying to init module: import-glpi
[1428497547] INFO: [Shinken] [GLPI Arbiter] I open the GLPI connection to http://localhost/glpi/plugins/webservices/xmlrpc.php
[1428497547] INFO: [Shinken] [GLPI Arbiter] Connection opened
[1428497547] INFO: [Shinken] [GLPI Arbiter] Authentication in progress
[1428497547] INFO: [Shinken] [GLPI Arbiter] Authenticated, session : 14khkp2d2f14no4u1jg06dof00
[1428497547] INFO: [Shinken] I correctly loaded the modules: [import-glpi,ws-arbiter]
[1428497547] ERROR: [Shinken] Instance import-glpi raised an exception <Fault 2: 'Unknown method (monitoring.shinkenHostgroups)'>. Log and continue to run
[1428497547] ERROR: [Shinken] Back trace of this remove: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 343, in load_config_file
    r = inst.get_objects()
  File "/var/lib/shinken/modules/import-glpi/module.py", line 149, in get_objects
    all_hostgroups = self.con.monitoring.shinkenHostgroups(arg)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 2: 'Unknown method (monitoring.shinkenHostgroups)'>

...
[/code]
Does I have to post the entire result ?

**Comment by ddurieux** [comment]
version of plugin monitoring ?

**Comment by algorys** [comment]
plugin monitoring 0.84+1.0
service web 1.4.3

**Comment by mohierf** [comment]
Hi David !

Are you using the last module.py as the one included in the repository ?

**Comment by algorys** [comment]
?!
Hmm, where I can find this ?
I'm using only the standard files... I've no download another file from other repository.
For monitoring I have take the tar here https://forge.indepnet.net/projects/monitoring/files

**Comment by ddurieux** [comment]
It's my fault, not have released the last version of plugin monitoring

Get this version: https://github.com/ddurieux/glpi_monitoring/archive/glpi0.84.zip (0.84+2.0b)

I will release in few hours

**Comment by mohierf** [comment]
Please check out the module.py file here : https://github.com/shinken-monitoring/mod-import-glpi/tree/master/module

And make a test with this version. I am not sure that the version currently installed with `shinken install` is running well :/P

I am currently testing a fresh install with @ddurieux

**Comment by algorys** [comment]
Ok... I follow @ddurieux or @mohierf ? ;)

**Comment by mohierf** [comment]
What I suggest : 
 1/ update your Monitoring plugin

 2/ if not successfull, test the last module.py file

**Comment by algorys** [comment]
ok. I will do that @mohierf and come back.

**Comment by algorys** [comment]
@ddurieux I have download your file but I can't find catalog on my plugin Monitoring now. Here is what I do : 

 wget https://github.com/ddurieux/glpi_monitoring/archive/glpi0.84.zip
 unzip glpi0.84.zip
 rm -R /var/www/glpi/plugins/monitoring/
 cp -R glpi_monitoring-glpi0.84/ /var/www/glpi/plugins/monitoring/

That's normal ?

**Comment by ddurieux** [comment]
Verify profile, between the 2 versions, we have added many rights and with migration they are disabled by default

**Comment by algorys** [comment]
Ok (good job, I'm little lost but that's great)

**Comment by algorys** [comment]
That's done. The good news is I have no more the error of the method !! 

The bad is I have no more graphics ^^ Maybe one day I'll get it. 

EDIT : I have always a bug with monitoring, when I had something or I restart shinken (in Linux CLI) I lost the main page of the plugin....

I have my PC (for the moment, I test only on one windows workstation) in state unknow, and ressources state OK... That's better than before.

And now I have something like this in Shinken : 

_fake_Root   DOWN10m 35s [Errno 2] No such file or directory

_fake_BP_host   UNREACHABLE5m 12s [Errno 2] No such file or directory  

_fake_rootentity   UNREACHABLE10m 38s [Errno 2] No such file or directory

Is it normal too ?

**Comment by mohierf** [comment]
Hosts prefixed by _fake are hosts built by the plugin Monitoring when it builds Shinken configuration. These hosts are useful in the Shinken WebUI to make groups and dependencies ...

 It is possible to change this behaviour with a variable in the inc/shinken.class.php file in the monitoring plugin files.

 At the very beginning of the file, you will find a variable named `$shinkenParameters` that contains many parameters that help configuring the Shinken configuration building.

 Please have a look at : 

```
         // Build fake hosts for parents relationship
         'fake_hosts' => array(
            // Default values
            'build' => true,
            // Fake hosts tag
            'use' => 'fake',
```

and change true to false for the build attribute. It is supposed to be correct ... not tested recently :-)

**Comment by algorys** [comment]
Ok. It does not bother me more than that. The shinken interface is right for me at the moment. But for the dashboard webpage, it's more annoying... I have to uninstall plugin et install again to get back the page each time.
That's doing it before I change this.

**Comment by mohierf** [comment]
Which dashboard page are you talking about ?

**Comment by algorys** [comment]
In GLPI. When I click on plugins > monitoring, I have have blank page under GLPI menus.

**Comment by mohierf** [comment]
Have a look at the profile management in Glpi (menu Administration / Profiles) and find the profile of your current account (eg Administrator). In this profile page, you will have a Monitoring tab that displays all the profile rights.

 Configure the different rights for as to see what your want on the Home page, on the plugin Monitoring page and in the dashboard ...

 I copy my configuration hereunder : 

![image](https://cloud.githubusercontent.com/assets/2932687/7046818/d0d47b4e-de08-11e4-9231-d4c4af61e611.png)

**Comment by algorys** [comment]
Yes I've already put all at "max" in the super-admin config. But I do not think it is due to this because it I was already doing before changing version ... When I install plugin, all is good, but if I restart Shinken, the page disappear.

**Comment by mohierf** [comment]
Did you logged out and logged in ?

I do not see any reason for which Shinken restarts should break this page ... except for any PHP error in the front/menu.php file ... this script checks for Shinken restart, components catalogs modifications, ... 

 Have a look in your php_errors.log and sql_errors.log in the Glpi log directory.

**Comment by algorys** [comment]
Ok. For the moment, I have reinstall plugins, so it's working. I will try to have at least one graphic for a ping before... because It says always status unknow ! Grrr.

A little question, for the nagios-plugins I have just install via apt-get, but is there another configuration to make ? Because I have the impression that he does not do well the controls or something like that.

EDIT : I have restart shinken in Linux directly, and it seems he have make my hosts via GLPI. Haha.

**Comment by algorys** [comment]
I obtained something like this in Shinken and GLPI : 

Warning: This plugin must be either run as root or setuid root. To run as root, you can use a tool like sudo. To set the setuid permissions, use the command: chmod u+s yourpluginfile check_icmp: Failed to obtain ICMP socket: Operation not permitted

**Comment by mohierf** [comment]
You nagios plugins is not directly executable from Shinken ...

You are logged in as shinken user and the check_icmp plugin must be allowed root privileges. Make `sudo chmod u+s check_icmp` to allow root privileges !

**Comment by algorys** [comment]
That works !! (pfewwww) 

Many, many thanks @mohierf  (and  @ddurieux too). I'm so happy. Two weeks of work to do that. Hugh.

**Comment by mohierf** [comment]
:+1:
