### ISSUE TITLE
[Shinken 2.2] GLPI: instance import-glpi raised an exception 'NoneType' object has no attribute 'monitoring'

### ISSUE THREAD

**Issue by vinnitino** [shinken-monitoring/mod-import-glpi#5]
Bonjour,

Hello,

I'm running Shinken 2.2, Monitoring GLPI plugin (0.85+1.3) and Webservices (1.5.1), I have managed to configure Monitoring to create a components catalogue however I'm not getting any updates on checks, indeed it's stating "UNKNOWN" for "Host state" column. I can see that the connection between GLPI (monitoring) and Shinken is well established (via Webservices).
However, here are two interesting points I've noticed:

1) If I run 'shinken-arbiter -v -c /etc/shinken/shinken.cfg', here is the only error that I get:

[1453804732] ERROR: [Shinken] Instance import-glpi raised an exception 'NoneType' object has no attribute 'monitoring'. Log and continue to run
[1453804732] ERROR: [Shinken] Back trace of this remove: Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/Shinken-2.2-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 343, in load_config_file
r = inst.get_objects()
File "/var/lib/shinken/modules/import-glpi/module.py", line 119, in get_objects
all_commands = self.con.monitoring.shinkenCommands(arg)
AttributeError: 'NoneType' object has no attribute 'monitoring'

2) Moreover, here is the output of /var/www/glpi/files/_log/webservices.log:
AccÃ¨s refusÃ© (anonymous, ::1, glpi.doLogin, xml-rpc)
-->It looks like Webservices is trying to establish a connection via IPv6 so it fails forever (while I'm able to restart Shinken from Monitoring plugin, so this is strange), right ? If that's the case how to circumvent it ?
Please could you advise ? 
Big thanks for the support.

**Comment by mohierf** [comment]
1st step: You must define a GLPI user and configure the username / password in `import-glpi.cfg` on your Shinken. If not, the Shinken module will not be able to get the configuration from the Glpi Web service.

2nd step: to have some information in Glpi about your hosts/services you muste use the Shinken module `glpidb` ... `import-glpi` is only used to set the Shinken configuration.

**Comment by vinnitino** [comment]
Thanks for the turbo reply!
1) This is already done.
2) I have run through what you advised successfully, as I'm not getting the "instance import-glpi raised an exception 'NoneType' object has no attribute 'monitoring'" message anymore, but this one now: "WARNING: [Shinken] The module type glpidb for glpidb was not found in modules!".
However, I still have that output from 'webservices.log': "AccÃ¨s refusÃ© (anonymous, 192.168.0.207, glpi.doLogin, xml-rpc)".
--> I have managed to avoid the connection establishing through IPv6, but I still have "anonymous" showed in the log whereas I've set glpi:glpi as username and password everywhere it needed to be specified (in ws-arbiter.cfg, in the webservices client config (GLPI side), in Monitoring plugin tag (GLPI side).

**Comment by mohierf** [comment]
For _glipdb_, you must `shinken install glpidb` to have the module on your server and then configure it and add it to the broker daemon modules list ... this part will allow to update MySQL database with the hosts/services states.

If you stil have an error with the Glpi WS, then your configuration is bad ...

1/ Did you create a user ?
2/ Make a test with this command `shinken-arbiter -v -c /etc/shinken/shinken.cfg` and you should see information about communication between Shinken and Glpi
3/ Did you add an entity tag to one of your Glpi entity and, if so, did you wrote this tag in `import-glpi.cfg` ? This is not mandatory ...

I copy my configuration file: 

```
define module {
    module_name     import-glpi
    module_type     import-glpi

    # Glpi Web service URI
    uri             http://192.168.0.15/glpi/plugins/webservices/xmlrpc.php
    # Default : shinken
    login_name      shinken
    # Default : shinken
    login_password  Shinken-2015

    # tags may contain a list of tags to get several entities from GLPI
    # When getting objects from several entities, the module deletes duplicate objects
    #tags            entity-1, entity-2, entity-3
    tags Demo
}
```

**Comment by vinnitino** [comment]
I have installed glpidb with shinken install glpidb as well as the other modules, and it is present in broker-master.cfg.
1) I have created a user named 'shinken', but I'm using the glpi default super-admin account instead of it.
2) Here is the only interesting part of shinken-arbiter -v -c /etc/shinken/shinken.cfg command output:

[1453815495] WARNING: [Shinken] The module type glpidb for glpidb was not found in modules!
[1453815495] INFO: [Shinken] [WS_Arbiter] Configuration done, host: 192.168.0.207(7760), username: glpi)
[1453815495] INFO: [Shinken] I correctly loaded the modules: [ws-arbiter]
3) I haven't add any entity tag on GLPI side.

Thanks.

**Comment by mohierf** [comment]
If your module import-glip is running well, in the `shinken-arbiter` command output you should have some logs like these: 

```
[1453817465] WARNING: [Shinken] [GLPI Arbiter] Got 6 contacts
[1453817465] INFO: [Shinken] [GLPI Arbiter] New contact: monitoring
[1453817465] INFO: [Shinken] [GLPI Arbiter] New contact: risit
[1453817465] INFO: [Shinken] [GLPI Arbiter] New contact: giraudw
[1453817465] INFO: [Shinken] [GLPI Arbiter] New contact: rubichonl
[1453817465] INFO: [Shinken] [GLPI Arbiter] New contact: tech_IPM
[1453817465] INFO: [Shinken] [GLPI Arbiter] New contact: mohier
[1453817465] WARNING: [Shinken] [GLPI Arbiter] Got 1 timeperiods
[1453817465] INFO: [Shinken] [GLPI Arbiter] New timeperiod: 24x7
[1453817465] WARNING: [Shinken] [GLPI Arbiter] Sending 48 commands to Arbiter
[1453817465] WARNING: [Shinken] [GLPI Arbiter] Sending 5 hosts to Arbiter
[1453817465] WARNING: [Shinken] [GLPI Arbiter] Sending 3 hosts groups to Arbiter
[1453817465] WARNING: [Shinken] [GLPI Arbiter] Sending 45 services templates to Arbiter
[1453817465] WARNING: [Shinken] [GLPI Arbiter] Sending 20 services to Arbiter
[1453817465] WARNING: [Shinken] [GLPI Arbiter] Sending 1 timeperiods to Arbiter
[1453817465] WARNING: [Shinken] [GLPI Arbiter] Sending 6 contacts to Arbiter
[1453817465] INFO: [Shinken] [GLPI Arbiter] Sending all data to Arbiter
```

First you need to fix this module before dealing with glidb ...

**Comment by vinnitino** [comment]
Here is what I have from the output of shinken-arbiter:

[1453816388] INFO: [Shinken] Running pre-flight check on configuration data...
[1453816388] INFO: [Shinken] Checking global parameters...
[1453816388] INFO: [Shinken] Checking hosts...
[1453816388] INFO: [Shinken]    Checked 1 hosts
[1453816388] INFO: [Shinken] Checking hostgroups...
[1453816388] INFO: [Shinken]    Checked 1 hostgroups
[1453816388] INFO: [Shinken] Checking contacts...
[1453816388] INFO: [Shinken]    Checked 2 contacts
[1453816388] INFO: [Shinken] Checking contactgroups...
[1453816388] INFO: [Shinken]    Checked 2 contactgroups
[1453816388] INFO: [Shinken] Checking notificationways...
[1453816388] INFO: [Shinken]    Checked 3 notificationways
[1453816388] INFO: [Shinken] Checking escalations...
[1453816388] INFO: [Shinken]    Checked 0 escalations
[1453816388] INFO: [Shinken] Checking services...
[1453816388] INFO: [Shinken]    Checked 0 services
[1453816388] INFO: [Shinken] Checking servicegroups...
[1453816388] INFO: [Shinken]    Checked 0 servicegroups
[1453816388] INFO: [Shinken] Checking timeperiods...
[1453816388] INFO: [Shinken]    Checked 4 timeperiods
[1453816388] INFO: [Shinken] Checking commands...
[1453816388] INFO: [Shinken]    Checked 23 commands
[1453816388] INFO: [Shinken] Checking hostsextinfo...
[1453816388] INFO: [Shinken]    Checked 0 hostsextinfo
[1453816388] INFO: [Shinken] Checking servicesextinfo...
[1453816388] INFO: [Shinken]    Checked 0 servicesextinfo
[1453816388] INFO: [Shinken] Checking checkmodulations...
[1453816388] INFO: [Shinken]    Checked 0 checkmodulations
[1453816388] INFO: [Shinken] Checking macromodulations...
[1453816388] INFO: [Shinken]    Checked 0 macromodulations
[1453816388] INFO: [Shinken] Checking servicedependencies...
[1453816388] INFO: [Shinken]    Checked 0 servicedependencies
[1453816388] INFO: [Shinken] Checking hostdependencies...
[1453816388] INFO: [Shinken]    Checked 0 hostdependencies
[1453816388] INFO: [Shinken] Checking arbiters...
[1453816388] INFO: [Shinken]    Checked 1 arbiters
[1453816388] INFO: [Shinken] Checking schedulers...
[1453816388] INFO: [Shinken]    Checked 1 schedulers
[1453816388] INFO: [Shinken] Checking reactionners...
[1453816388] INFO: [Shinken]    Checked 1 reactionners
[1453816388] INFO: [Shinken] Checking pollers...
[1453816388] INFO: [Shinken]    Checked 1 pollers
[1453816388] INFO: [Shinken] Checking brokers...
[1453816388] INFO: [Shinken]    Checked 1 brokers
[1453816388] INFO: [Shinken] Checking receivers...
[1453816388] INFO: [Shinken]    Checked 1 receivers
[1453816388] INFO: [Shinken] Checking resultmodulations...
[1453816388] INFO: [Shinken]    Checked 0 resultmodulations
[1453816388] INFO: [Shinken] Checking discoveryrules...
[1453816388] INFO: [Shinken]    Checked 0 discoveryrules
[1453816388] INFO: [Shinken] Checking discoveryruns...
[1453816388] INFO: [Shinken]    Checked 0 discoveryruns
[1453816388] INFO: [Shinken] Checking businessimpactmodulations...
[1453816388] INFO: [Shinken]    Checked 0 businessimpactmodulations
[1453816388] INFO: [Shinken] Cutting the hosts and services into parts
[1453816388] INFO: [Shinken] Creating packs for realms
[1453816388] INFO: [Shinken] Number of hosts in the realm All: 1 (distributed in
[1453816388] INFO: [Shinken] Total number of hosts : 1
[1453816388] INFO: [Shinken] Things look okay - No serious problems were detected

However, I have not uncommented 'cfg_dir' lines in shinken.cfg, I've read somewhere that this was necessary ? could it be the root cause of my issue ?

**Comment by vinnitino** [comment]
Ok, I had deleted "import_glpi" from arbiter, so it could not work properly... however my 4 hosts in the component catalogue I created before are now in critical state (while they are reachable via ping) and the message under the 'Resultat' column is "[Errno 2] No such file or directory".

**Comment by mohierf** [comment]
It seems that you database is updating ... and that you host checks are not correct.

Did you install the Shinken WebUI ? If so, you can have a look at your host states to confirm that the plugins you are using to check are running well ...

You can have a look in the `brokerd.log` log file to check if they are any errors with the `glpidb` module.

**Comment by vinnitino** [comment]
The problem is now solved, I have been able to do so by setting the $PLUGINSDIR$ var to the correct folder ("[Errno 2] No such file or directory". meant that it could not find the perl scripts folder).
Thanks a lot for your support and your readiness mohierf !
