### ISSUE TITLE
WS connection error: ProtocolError for xmlrpc.php

### ISSUE THREAD

**Issue by algorys** [shinken-monitoring/mod-import-glpi#8]
Hello,

I'm trying to make my installation with GLPI and Shinken working but I encounter some problem with the web-services connection.

Here is my configuration : 

One server GLPI (0.90.1) with following plugins : 
- Monitoring    0.90+1.0
- Services Web  1.6.0

One server with Shinken (2.4.2) with following modules : 
- import-glpi
- ws-arbiter
- glpidb
- webui2

Connection to databse is working but webservice won't works... :'(

Here is my log : 

``` bash
[1457628421] ERROR: [Shinken] [GLPI Arbiter] WS connection error: <ProtocolError for 192.168.31.134/glpi/plugins/webservices/xmlrpc.php: 404 Not Found>
[1457628421] ERROR: [Shinken] [GLPI Arbiter] No opened session, no objects to provide.
[1457628421] ERROR: [Shinken] Instance import-glpi raised an exception 'NoneType' object has no attribute 'monitoring'. Log and continue to run
```

And if I run `shinken-arbiter -v -c /etc/shinken/shinken.cfg` here is what I have : 

``` bash
[1457629366] INFO: [Shinken] Trying to init module: import-glpi
[1457629366] INFO: [Shinken] [GLPI Arbiter] Connecting to http://192.168.31.134/glpi/plugins/webservices/xmlrpc.php
[1457629366] INFO: [Shinken] [GLPI Arbiter] Connection opened
[1457629366] INFO: [Shinken] [GLPI Arbiter] Authentication in progress...
[1457629366] ERROR: [Shinken] [GLPI Arbiter] WS connection error: <ProtocolError for 192.168.31.134/glpi/plugins/webservices/xmlrpc.php: 404 Not Found>
[1457629366] INFO: [Shinken] I correctly loaded the modules: [import-glpi]
[1457629366] ERROR: [Shinken] [GLPI Arbiter] No opened session, no objects to provide.
[1457629366] INFO: [Shinken] [GLPI Arbiter] Tags (from configuration): ['']
[1457629366] INFO: [Shinken] [GLPI Arbiter] Getting configuration for entity tagged with ''
[1457629366] ERROR: [Shinken] Instance import-glpi raised an exception 'NoneType' object has no attribute 'monitoring'. Log and continue to run
[1457629366] ERROR: [Shinken] Back trace of this remove: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 502, in load_modules_configuration_objects
    r = inst.get_objects()
  File "/var/lib/shinken/modules/import-glpi/module.py", line 119, in get_objects
    all_commands = self.con.monitoring.shinkenCommands(arg)
AttributeError: 'NoneType' object has no attribute 'monitoring'

[1457629366] INFO: [Shinken] All: (in/potential) (schedulers:1) (pollers:1/1) (reactionners:1/1) (brokers:1/1) (receivers:1/1)
[1457629366] WARNING: [Shinken] The following parameter(s) are not currently managed.
```

I've seen in this issue #5 that I have to set a tag, but I can't make a tag in my GLPI web interface...

I've tried many URI in doubt : 

```
http://192.168.31.134/glpi/plugins/webservices/xmlrpc.php
http://192.168.31.134/plugins/webservices/xmlrpc.php
http://FQDN/glpi/plugins/webservices/xmlrpc.php
```

But nothing work.

I've make a user shinken in GLPI and put in my import-glpi.cfg, I've configure my webservice on glpi like this : 

```
Nom  shinken
Services actifs  Oui
Activer la compression  Non
Tracer les connexions   Non
Debug   Oui
Motif SQL des services  .*
Plage d'adresses IPv4   192.168.31.135 - 192.168.31.135
```

If you may help please.

Thanks

**Comment by mohierf** [comment]
1/ check that your web service connection is ok. The history tab in the web service will inform you about this ...

 2/ You can set a monitoring tag to an entity in Glpi in the **Monitoring** tab of the entity. The _import-glpi_ Shinken module will import only the hosts of this entity and of its children entities.

**Comment by algorys** [comment]
Thanks @mohierf for help.

1/ In my history TAb of webservice, I've only modifications I do. But in methods tab I've all set to `yes`. I've always this error : 

``` bash
[1457689005] INFO: [Shinken] Trying to init module: import-glpi
[1457689005] INFO: [Shinken] [GLPI Arbiter] Connecting to http://192.168.31.134/glpi/plugins/webservices/xmlrpc.php
[1457689005] INFO: [Shinken] [GLPI Arbiter] Connection opened
[1457689005] INFO: [Shinken] [GLPI Arbiter] Authentication in progress...
[1457689005] ERROR: [Shinken] [GLPI Arbiter] WS connection error: <ProtocolError for 192.168.31.134/glpi/plugins/webservices/xmlrpc.php: 404 Not Found>
[1457689005] INFO: [Shinken] I correctly loaded the modules: [import-glpi]
[1457689005] ERROR: [Shinken] [GLPI Arbiter] No opened session, no objects to provide.
[1457689005] INFO: [Shinken] [GLPI Arbiter] Tags (from configuration): ['']
[1457689005] INFO: [Shinken] [GLPI Arbiter] Getting configuration for entity tagged with ''
[1457689005] ERROR: [Shinken] Instance import-glpi raised an exception 'NoneType' object has no attribute 'monitoring'. Log and continue to run
[1457689005] ERROR: [Shinken] Back trace of this remove: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 502, in load_modules_configuration_objects
    r = inst.get_objects()
  File "/var/lib/shinken/modules/import-glpi/module.py", line 119, in get_objects
    all_commands = self.con.monitoring.shinkenCommands(arg)
AttributeError: 'NoneType' object has no attribute 'monitoring'
```

I do not see where is my error...

2/ If I go to entity configuration, tab  and I save a tag (like "monitoring" for example). He save data but if I go to monitoring plugin configuration, tab `tag` there is no tag available....

Something I've not put before, in my `glpi/files/_log/*.log` I've the following log (I've not found webservices log ... ?!) : 

``` bash
2016-03-11 10:44:59 [2@srv-glpi]
sendRestartArbiter, command : restart, tag: 0, force: 0
2016-03-11 10:44:59 [2@srv-glpi]
sendRestartArbiter, no tag specified

==> files/_log/cron.log <==
2016-03-11 10:44:59 [2@srv-glpi]
Interne #1 : Démarrage queuedmail

==> files/_log/pm-restart.log <==
2016-03-11 10:46:22 [2@srv-glpi]
sendRestartArbiter, command : restart, tag: 0, force: 0
2016-03-11 10:46:22 [2@srv-glpi]
sendRestartArbiter, no tag specified
```

**Comment by ddurieux** [comment]
You have a 404 (file not found) on 192.168.31.134/glpi/plugins/webservices/xmlrpc.php so be sure you have installer webservice plugin correctly

**Comment by algorys** [comment]
Erf, how stupid I am...

I've put adress with FQDN : `http://glpi.local.fr/plugins/webservices/xmlrpc.php` and that's working.

Sorry... I close issue
